---
- hosts: localhost
  become: true
  connection: local
  vars:
    kea_dhcp_debian_packages:
      - 'kea-admin'
      - 'kea-dhcp-ddns-server'
      - 'kea-dhcp4-server'
  tasks:
    - name: Updating Apt-Cache
      apt:
        update_cache: yes

    - name: Installing Kea DHCP
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items: '{{ kea_dhcp_debian_packages }}'

    - name: Ensuring Folders Exist
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/var/log/kea'

    - name: Configuring Kea
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: '/kea-dhcp4.conf.j2'
          dest: '/etc/kea/kea-dhcp4.conf'

    - name: Creating Symlink(s)
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: "link"
      with_items:
        - src: '/etc/kea/kea-dhcp4.conf'
          dest: '/etc/kea/kea.conf'
